homes page with adaptive and map
dshubenok/airbnb-demo-frontend pull request #2
Opened 2017-11-17 08:10 UTC by dshubenok

https://build-euslasfuep.now.sh

2017-11-17 12:33 UTC, evgenyrodionov commented
Это что за красота ❤️

![image](https://user-images.githubusercontent.com/775692/32947385-ac073290-cbac-11e7-95f4-9747117e9c7f.png)

2017-11-17 12:37 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/32947485-167e656c-cbad-11e7-854d-4c088ee78705.png)

У хедера отступа большие внутренние
![image](https://user-images.githubusercontent.com/775692/32947489-1cfbb278-cbad-11e7-8e91-753f3c9e13f3.png)

В футере тоже поехало всё
![image](https://user-images.githubusercontent.com/775692/32947518-280133be-cbad-11e7-93bd-5a032be449cb.png)

С главной никак на Homes попасть нельзя

2017-11-17 12:38 UTC, evgenyrodionov commented
Какие-то разные контейнеры
![image](https://user-images.githubusercontent.com/775692/32947683-3cfe5904-cbad-11e7-9af1-fdff0a0adace.png)

2017-11-17 12:40 UTC, imevro requested changes

2017-11-17 12:40 UTC, evgenyrodionov commented on src/Homes/index.js
> +                  <Map center={{ lat: 45, lng: 20 }} zoom={10} />
читай доку нашу

2017-11-17 12:40 UTC, evgenyrodionov commented on src/Homes/styled.js
> +  left: calc(((992px) / 12 * 8 + (100% - 992px) / 2) + 8px);
блядь что

2017-11-18 08:41 UTC, dshubenok commented
https://build-nhjswxbcso.now.sh

2017-11-18 11:16 UTC, evgenyrodionov commented
Вижу игнор замечания, не проверяю 

https://github.com/dshubenok/airbnb-demo-frontend/pull/2#discussion_r151675128

2017-11-18 20:49 UTC, dshubenok commented
https://build-smoowscdjb.now.sh

2017-11-18 22:34 UTC, dshubenok commented
https://build-uhcolvuusk.now.sh

2017-11-19 23:53 UTC, closed without merging

2017-11-19 23:53 UTC, evgenyrodionov commented
Копипасту не принимаю